# Generated by Django 5.0.7 on 2024-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='fullname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
