# Generated by Django 5.0.7 on 2024-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_otp_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='fullname',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
