# Generated by Django 5.0.7 on 2024-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('phone', 'code')},
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('token', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'unique_together': {('phone', 'code')},
            },
        ),
    ]
