# Generated by Django 5.0.7 on 2024-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
