# Generated by Django 5.0.7 on 2024-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_address_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
    ]
