# Generated by Django 5.0.7 on 2024-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_remove_address_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
