# Generated by Django 5.0.7 on 2024-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
