# Generated by Django 5.0.7 on 2024-08-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='تصاویر محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'سایز',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.SmallIntegerField(blank=True, default=0, help_text='این فیلد اجباری نیست', null=True, verbose_name='مبلغ قبل تخفیف')),
                ('image', models.ImageField(upload_to='products', verbose_name='تصویر محصول')),
                ('category', models.ManyToManyField(to='product.category')),
                ('color', models.ManyToManyField(related_name='products', to='product.color', verbose_name='رنگ')),
                ('gallery', models.ManyToManyField(related_name='gallery', to='product.gallery', verbose_name='تصایر')),
                ('size', models.ManyToManyField(related_name='products', to='product.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='عنوان ویژگی')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه',
                'verbose_name_plural': 'مشخصات',
            },
        ),
    ]
