# Generated by Django 5.0.7 on 2024-08-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_address_linkmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='linkmap',
            new_name='link_map',
        ),
    ]
