# Generated by Django 5.0.7 on 2024-09-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
