# Generated by Django 5.0.7 on 2024-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
