# Generated by Django 5.0.7 on 2024-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='size'),
        ),
    ]
