# Generated by Django 5.0.7 on 2024-08-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_order_shipping_type_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
