# Generated by Django 5.0.7 on 2024-08-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orderitem_shipping_orderitem_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_total',
        ),
    ]
