# Generated by Django 5.0.7 on 2024-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_shipping_options_alter_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.SmallIntegerField(default=0)),
                ('quantity', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
