# Generated by Django 5.0.7 on 2024-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_discountcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیفات'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percentage',
            field=models.SmallIntegerField(default=0, verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
    ]
